import React from 'react';
import {ScrollView,View,Text,StyleSheet,TouchableOpacity} from 'react-native';
import {subjects} from '../data';

const guides:Record<string,{overview:string;points:string[];exam:string[]}>={
  'maths1-01':{overview:'Linear equations in two variables involve two unknown quantities and can be represented graphically by a straight line.',points:['Write the equation in a clear standard form.','Use substitution or elimination when solving a pair of equations.','Check the values by substituting them back into both equations.','For graphical solutions, the intersection point represents the solution.'],exam:['Show all algebraic steps.','Write the final ordered pair clearly.','Verify the answer when time permits.']},
  'science1-01':{overview:'Gravitation describes the attractive force between masses and explains phenomena such as falling objects and planetary motion.',points:['Gravitational force depends on mass and distance.','Acceleration due to gravity is commonly represented by g.','Mass remains constant while weight depends on gravitational acceleration.','Use correct SI units in numerical answers.'],exam:['Write the formula before substitution.','Include units in the final answer.','Keep numerical working neat and sequential.']},
  'science1-04':{overview:'Electric current produces several useful effects and is applied in household devices, heating appliances and electromagnetic systems.',points:['Current is the rate of flow of electric charge.','Heating effect is used in appliances such as heaters and irons.','Electrical safety depends on suitable wiring, insulation and protective devices.','Use circuit symbols and units correctly.'],exam:['Draw labelled circuit diagrams where required.','State the relevant law or formula before solving numericals.','Mention SI units.']}
};

export function ChapterReaderScreen({route,navigation}:any){
 const {subjectId,chapterId}=route.params; const subject=subjects.find(x=>x.id===subjectId); const chapter=subject?.chapters.find(x=>x.id===chapterId); if(!subject||!chapter)return null;
 const guide=guides[chapterId]||{overview:`This chapter is part of ${subject.name}. Use this study guide to build concepts, revise important ideas and prepare for board-style questions.`,points:['Read the chapter concept-by-concept.','Create short revision notes in your own words.','Practise examples before attempting timed questions.','Review mistakes after every practice session.'],exam:['Answer according to the marks allotted.','Use keywords, steps and labelled diagrams where appropriate.','Keep the final answer clear and easy to evaluate.']};
 return <ScrollView style={s.bg} contentContainerStyle={s.pad}><Text style={s.kicker}>CHAPTER {chapter.number}</Text><Text style={s.h}>{chapter.title}</Text><Text style={s.sub}>{subject.name} • Study Guide</Text><View style={s.hero}><Text style={s.heroTitle}>Concept overview</Text><Text style={s.body}>{guide.overview}</Text></View><Text style={s.section}>Key points</Text>{guide.points.map((p,i)=><View key={i} style={s.point}><Text style={s.num}>{i+1}</Text><Text style={s.body}>{p}</Text></View>)}<Text style={s.section}>Board exam tips</Text>{guide.exam.map((p,i)=><View key={i} style={s.tip}><Text style={s.check}>✓</Text><Text style={s.body}>{p}</Text></View>)}<TouchableOpacity style={s.button} onPress={()=>navigation.navigate('QuestionBank',{subjectId,chapterId})}><Text style={s.buttonText}>Practice Question Bank →</Text></TouchableOpacity><Text style={s.note}>This is an original study guide, not a reproduction of textbook pages. Verified chapter material can be added to this structure later.</Text></ScrollView>}
const s=StyleSheet.create({bg:{flex:1,backgroundColor:'#F7F8FC'},pad:{padding:20,paddingBottom:48},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1,color:'#4F46E5'},h:{fontSize:27,fontWeight:'800',color:'#172033',marginTop:6},sub:{fontSize:14,color:'#6B7280',marginTop:5},hero:{backgroundColor:'#EEF2FF',borderRadius:18,padding:18,marginTop:18},heroTitle:{fontSize:17,fontWeight:'800',color:'#312E81',marginBottom:7},body:{fontSize:14,lineHeight:21,color:'#374151',flex:1},section:{fontSize:20,fontWeight:'800',color:'#172033',marginTop:24,marginBottom:10},point:{backgroundColor:'#FFF',borderRadius:15,padding:15,marginBottom:9,flexDirection:'row',gap:12,borderWidth:1,borderColor:'#EEF0F4'},num:{width:26,height:26,borderRadius:13,backgroundColor:'#EDE9FE',textAlign:'center',textAlignVertical:'center',fontWeight:'800',color:'#6D28D9',overflow:'hidden'},tip:{backgroundColor:'#FFF',borderRadius:15,padding:15,marginBottom:9,flexDirection:'row',gap:12,borderWidth:1,borderColor:'#EEF0F4'},check:{fontSize:18,fontWeight:'800',color:'#16A34A'},button:{backgroundColor:'#4F46E5',padding:16,borderRadius:15,alignItems:'center',marginTop:20},buttonText:{color:'#FFF',fontSize:15,fontWeight:'800'},note:{marginTop:14,padding:14,backgroundColor:'#FFF7ED',borderRadius:14,color:'#9A3412',lineHeight:19,fontSize:12}});
