import React from'react';import{ScrollView,View,Text,StyleSheet}from'react-native';import{subjects,student}from'../data';import{useTheme}from'../theme/ThemeProvider';

const scores:Record<string,number>={marathi:76,english:84,hindi:79,maths1:72,maths2:81,science1:88,science2:86,history:74,political:80,geography:83};

export function ProgressScreen(){const{colors}=useTheme();const overall=Math.round(Object.values(scores).reduce((a,b)=>a+b,0)/Object.values(scores).length);const gap=Math.max(0,student.targetPercentage-overall);const strong=subjects.filter(x=>(scores[x.id]||0)>=85);const weak=subjects.filter(x=>(scores[x.id]||0)<78);return <ScrollView style={[s.bg,{backgroundColor:colors.background}]} contentContainerStyle={{paddingBottom:32}}><View style={s.header}><Text style={[s.kicker,{color:colors.primary}]}>YOUR JOURNEY</Text><Text style={[s.h,{color:colors.text}]}>Progress & Analytics 📈</Text><Text style={[s.muted,{color:colors.muted}]}>Keep going, Sanvi. Every practice session counts.</Text></View>

<View style={[s.hero,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={{flex:1}}><Text style={[s.label,{color:colors.primary}]}>OVERALL PERFORMANCE</Text><Text style={[s.big,{color:colors.text}]}>{overall}%</Text><Text style={[s.small,{color:colors.muted}]}>{gap===0?'🎯 Target reached!':'Only '+gap+'% to your '+student.targetPercentage+'% target'}</Text></View><View style={[s.ring,{borderColor:colors.primary}]}><Text style={[s.ringText,{color:colors.primary}]}>{student.targetPercentage}%</Text><Text style={[s.ringLabel,{color:colors.muted}]}>TARGET</Text></View></View>

<View style={s.grid}>{[['12','Tests','📝'],['76%','Average','⭐'],['92%','Best','🏆'],['18h','Study time','⏱️']].map(x=><View key={x[1]} style={[s.stat,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={s.emoji}>{x[2]}</Text><Text style={[s.num,{color:colors.text}]}>{x[0]}</Text><Text style={[s.sub,{color:colors.muted}]}>{x[1]}</Text></View>)}</View>

<View style={[s.streak,{backgroundColor:colors.primary}]}><Text style={s.streakEmoji}>🔥</Text><View style={{flex:1}}><Text style={s.streakTitle}>7 day study streak</Text><Text style={s.streakSub}>You’re building a great habit. Don’t break it today!</Text></View><Text style={s.streakNum}>7</Text></View>

<Text style={[s.section,{color:colors.text}]}>Subject performance</Text><View style={[s.card,{backgroundColor:colors.surface,borderColor:colors.border}]}>{subjects.map(x=>{const value=scores[x.id]||0;return <View key={x.id} style={s.subject}><View style={s.subjectTop}><Text numberOfLines={1} style={[s.subjectName,{color:colors.text}]}>{x.name}</Text><Text style={[s.score,{color:value>=85?colors.success:value<78?colors.danger:colors.primary}]}>{value}%</Text></View><View style={[s.track,{backgroundColor:colors.border}]}><View style={[s.fill,{width:`${value}%`,backgroundColor:value>=85?colors.success:value<78?colors.warning:colors.primary}]}/></View></View>})}</View>

<View style={s.two}><View style={[s.miniCard,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={s.miniIcon}>💪</Text><Text style={[s.miniTitle,{color:colors.text}]}>Strong areas</Text>{strong.slice(0,3).map(x=><Text key={x.id} style={[s.bullet,{color:colors.muted}]}>• {x.shortName} — {scores[x.id]}%</Text>)}<Text style={[s.hint,{color:colors.success}]}>Keep these strong</Text></View><View style={[s.miniCard,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={s.miniIcon}>🎯</Text><Text style={[s.miniTitle,{color:colors.text}]}>Focus next</Text>{weak.slice(0,3).map(x=><Text key={x.id} style={[s.bullet,{color:colors.muted}]}>• {x.shortName} — {scores[x.id]}%</Text>)}<Text style={[s.hint,{color:colors.warning}]}>Revise these first</Text></View></View>

<Text style={[s.section,{color:colors.text}]}>Recent activity</Text><View style={[s.card,{backgroundColor:colors.surface,borderColor:colors.border}]}>{[['📝','Daily Test','Completed · 8/10'],['📚','Science revision','Chapter practice'],['⚡','Maths practice','12 questions solved']].map(x=><View key={x[1]} style={s.activity}><Text style={s.activityIcon}>{x[0]}</Text><View style={{flex:1}}><Text style={[s.activityTitle,{color:colors.text}]}>{x[1]}</Text><Text style={[s.activitySub,{color:colors.muted}]}>{x[2]}</Text></View><Text style={[s.done,{color:colors.success}]}>✓</Text></View>)}</View></ScrollView>}

const s=StyleSheet.create({bg:{flex:1,padding:20},header:{marginBottom:18},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.2},h:{fontSize:28,fontWeight:'900',marginTop:5},muted:{fontSize:13,lineHeight:20},hero:{padding:20,borderRadius:22,borderWidth:1,flexDirection:'row',alignItems:'center',marginBottom:14},label:{fontSize:10,fontWeight:'900',letterSpacing:.8},big:{fontSize:48,fontWeight:'900',marginVertical:2},small:{fontSize:12},ring:{width:82,height:82,borderRadius:41,borderWidth:8,alignItems:'center',justifyContent:'center'},ringText:{fontSize:17,fontWeight:'900'},ringLabel:{fontSize:8,fontWeight:'800',marginTop:1},grid:{flexDirection:'row',flexWrap:'wrap',gap:9,marginBottom:14},stat:{width:'48%',padding:15,borderRadius:17,borderWidth:1},emoji:{fontSize:19,marginBottom:5},num:{fontSize:23,fontWeight:'900'},sub:{fontSize:11,marginTop:2},streak:{borderRadius:20,padding:17,flexDirection:'row',alignItems:'center',marginBottom:22},streakEmoji:{fontSize:27,marginRight:12},streakTitle:{color:'#FFF',fontWeight:'900',fontSize:16},streakSub:{color:'#FFF',opacity:.86,fontSize:11,marginTop:3},streakNum:{color:'#FFF',fontSize:30,fontWeight:'900'},section:{fontSize:19,fontWeight:'900',marginBottom:10},card:{padding:16,borderRadius:19,borderWidth:1,marginBottom:18},subject:{marginBottom:14},subjectTop:{flexDirection:'row',alignItems:'center',marginBottom:7},subjectName:{flex:1,fontSize:13,fontWeight:'700'},score:{fontSize:13,fontWeight:'900'},track:{height:8,borderRadius:8,overflow:'hidden'},fill:{height:8,borderRadius:8},two:{flexDirection:'row',gap:10,marginBottom:20},miniCard:{flex:1,padding:15,borderRadius:18,borderWidth:1,minHeight:160},miniIcon:{fontSize:22,marginBottom:8},miniTitle:{fontSize:14,fontWeight:'900',marginBottom:8},bullet:{fontSize:11,lineHeight:20},hint:{fontSize:10,fontWeight:'900',marginTop:8},activity:{flexDirection:'row',alignItems:'center',paddingVertical:10},activityIcon:{fontSize:20,width:38},activityTitle:{fontSize:13,fontWeight:'800'},activitySub:{fontSize:11,marginTop:2},done:{fontSize:18,fontWeight:'900'}});